version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  nginx:
    build: ./nginx
    domainname: app.local
    hostname: nginx
    ports:
      - 0.0.0.0:8000:80
    links:
      - frontend

  frontend:
    build: ./frontend
    domainname: app.local
    hostname: frontend
    expose:
      - 5000
    links:
      - mongodb
      - influxdb
 
  mongodb:
    build: ./mongodb
    domainname: app.local
    hostname: mongo
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /var/lib/mongodb/:/data/db

  influxdb:
    build: ./influxdb
    domainname: app.local
    hostname: influx
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

  telegraf:
    build: ./telegraf
    domainname: app.local
    hostname: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8094:8094
    links:
      - influxdb
      - mongodb
      - nginx

  chronograf:
    build: ./chronograf
    domainname: app.local
    hostname: chronograf
    ports:
      - 8888:8888
    links:
      - influxdb
volumes:
  influxdb:
