version: '3'

services:
  nginx:
    build: ./nginx
    domainname: app.local
    hostname: nginx
    links:
      - frontend
    ports:
      - 0.0.0.0:8000:80
    volumes:
      - nginx:/etc/nginx

  frontend:
    build: ./frontend
    domainname: app.local
    hostname: frontend
    expose:
      - 5000
    links:
      - mongodb
      - influxdb
 
  mongodb:
    build: ./mongodb
    domainname: app.local
    hostname: mongo
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /var/lib/mongodb/:/data/db

  influxdb:
    build: ./influxdb
    domainname: app.local
    hostname: influx
    expose:
      - 8086
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  mongodb:
  influxdb:
  nginx:
